#!/bin/bash

npx browserify ./src/script.require.js -o ./dist/browserify.bundle.js

echo  '**** use port generated by http-server ****'
echo  '**** open http://127.0.0.1:8080/[port]/index.browserify.html ****'

npx http-server
